### ISSUE TITLE
MongoDB adapter error after upgrading to v7.0.4

### ISSUE THREAD

**Issue by UsingNamespaceNolan** [Jaspersoft/jasperreports#578]
Recently I tried to upgrade Jasper Library from v6.21.5 to v7.0.4 but I am getting an error regarding the MongoDB Data Adapter:

java.lang.NoClassDefFoundError: 
Could not initialize class com.jaspersoft.mongodb.adapter.MongoDbDataAdapterServiceExtensionsRegistryFactory with root cause java.lang.ExceptionInInitializerError: 
Exception java.lang.NoClassDefFoundError: 
net/sf/jasperreports/data/DataAdapterContributorFactory 
at com.jaspersoft.mongodb.adapter.MongoDbDataAdapterServiceExtensionsRegistryFactory 

It seems like the latest MongoDB datasource connector (js-mongodb-datasource v3.10.2) does not work with Jasper Library version 7.0.4.

Are there any options to use a MongoDB connector with Jasper Library 7.x?

**Comment by teodord** [comment]
The MongoDb connector for JasperReports is no longer part of the community edition of Jaspersoft Studio starting with version 7.
For an updated version of this connector, you can contact Jaspersoft.
